/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package c.securebank.view;
import c.securebank.controller.controllerUsuario;
import java.awt.event.*;
import c.securebank.ConectaBD;
import java.sql.SQLException;
import java.util.logging.Logger;
import java.util.logging.Level;
import javax.swing.*;



public class logotipo extends javax.swing.JPanel {
    
    private JButton btnAtualizarSaldo;

    
    public logotipo() {
        initComponents();
        atualizarSaldo();
        saque saquerealizado = new saque();
        deposito depositorealizado = new deposito();
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblogo = new javax.swing.JLabel();
        lbconta = new javax.swing.JLabel();
        lbagencia = new javax.swing.JLabel();
        lbnumeragencia = new javax.swing.JLabel();
        txtNumeroConta = new javax.swing.JLabel();
        lbseparador = new javax.swing.JLabel();
        lbsaldo = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(26, 32, 44));

        lblogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/c/securebank/resources/icons8-usuário-homem-com-círculo-100.png"))); // NOI18N

        lbconta.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbconta.setForeground(new java.awt.Color(255, 255, 255));
        lbconta.setText("Conta:");

        lbagencia.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbagencia.setForeground(new java.awt.Color(255, 255, 255));
        lbagencia.setText("Agência:");

        lbnumeragencia.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbnumeragencia.setForeground(new java.awt.Color(255, 255, 255));
        lbnumeragencia.setText("0001");

        txtNumeroConta.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txtNumeroConta.setForeground(new java.awt.Color(255, 255, 255));
        txtNumeroConta.setText("12345-6");

        lbseparador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbseparador.setForeground(new java.awt.Color(255, 255, 255));
        lbseparador.setText("|");

        lbsaldo.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbsaldo.setForeground(new java.awt.Color(255, 255, 255));
        lbsaldo.setText("Saldo: R$");

        txtSaldo.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txtSaldo.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/c/securebank/resources/icons8-recarregar-24.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbsaldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSaldo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbagencia)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbnumeragencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbseparador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbconta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumeroConta))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblogo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                .addComponent(jLabel1)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblogo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbconta)
                    .addComponent(lbagencia)
                    .addComponent(lbnumeragencia)
                    .addComponent(txtNumeroConta)
                    .addComponent(lbseparador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbsaldo)
                    .addComponent(txtSaldo))
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        atualizarSaldo();
    }//GEN-LAST:event_jLabel1MouseClicked
    
    private void atualizarSaldo() {
        ConectaBD banco = new ConectaBD();
        controllerUsuario conexao = new controllerUsuario();
        login teste = new login();

        double saldo = conexao.obterSaldo(teste.username);
        int numeroConta;
        try {
            numeroConta = conexao.obterNumeroConta(teste.username);
            String numeroContaf = String.format("%05d-%d", numeroConta / 10, numeroConta % 10);
            txtNumeroConta.setText(String.valueOf(numeroContaf));
        } catch (SQLException ex) {
            Logger.getLogger(logotipo.class.getName()).log(Level.SEVERE, null, ex);
        }
        String saldof = String.format("%.2f", saldo);
        txtSaldo.setText(String.valueOf(saldof));
        banco.fecharConexao();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbagencia;
    private javax.swing.JLabel lbconta;
    private javax.swing.JLabel lblogo;
    private javax.swing.JLabel lbnumeragencia;
    private javax.swing.JLabel lbsaldo;
    private javax.swing.JLabel lbseparador;
    private javax.swing.JLabel txtNumeroConta;
    private javax.swing.JLabel txtSaldo;
    // End of variables declaration//GEN-END:variables

}
