/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package c.securebank.view;

import c.securebank.ConectaBD;
import c.securebank.controller.controllerEndereco;
import c.securebank.controller.controllerUsuario;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author B4RB4N£GR4
 */
public class mudardados extends javax.swing.JPanel {

    public mudardados() {
        initComponents();
        // Adiciona um ouvinte de ação ao botão de rádio rbdados
        rbdados.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (rbdados.isSelected()) {
                    cbDados.removeAllItems();
                    cbDados.addItem("Nome");
                    cbDados.addItem("Nome de Usuario");
                    cbDados.addItem("Senha");
                }
            }
        });

        // Adiciona um ouvinte de ação ao botão de rádio rbendereco
        rbendereco.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (rbendereco.isSelected()) {
                    cbDados.removeAllItems();
                    cbDados.addItem("Rua");
                    cbDados.addItem("Número");
                    cbDados.addItem("Setor");
                    cbDados.addItem("Cidade");
                    cbDados.addItem("Estado");
                    cbDados.addItem("CEP");
                    cbDados.addItem("Complemento");
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rbdados = new javax.swing.JRadioButton();
        rbendereco = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        cbDados = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtNovoDado = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(26, 32, 44));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/c/securebank/resources/icons8-alterar-usuário-masculino-48.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(4, 191, 85));
        jLabel3.setText("Mudar Dados");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("<html>\nNa SecureBank, acreditamos que a segurança e a conveniência andam de mãos dadas.<br> \nCom nossa nova e aprimorada funcionalidade de \"Mudança de Dados\", você tem o <br>\npoder de atualizar suas informações pessoais com facilidade e rapidez, tudo isso<br> \nenquanto mantemos o mais alto padrão de segurança para garantir sua tranquilidade.</html>");
        jLabel2.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CATEGORIA:");

        rbdados.setBackground(new java.awt.Color(26, 32, 44));
        buttonGroup1.add(rbdados);
        rbdados.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        rbdados.setForeground(new java.awt.Color(255, 255, 255));
        rbdados.setText("DADOS PESSOAIS");
        rbdados.setToolTipText("");
        rbdados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rbdados.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        rbendereco.setBackground(new java.awt.Color(26, 32, 44));
        buttonGroup1.add(rbendereco);
        rbendereco.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        rbendereco.setForeground(new java.awt.Color(255, 255, 255));
        rbendereco.setText("ENDEREÇO");
        rbendereco.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel4.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DADO QUE DESEJA MUDAR:");

        cbDados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- SELECIONE --" }));

        jLabel6.setBackground(new java.awt.Color(26, 32, 44));
        jLabel6.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NOVO DADO:");

        txtNovoDado.setBackground(new java.awt.Color(26, 32, 44));
        txtNovoDado.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txtNovoDado.setForeground(new java.awt.Color(255, 255, 255));
        txtNovoDado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNovoDado.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(4, 191, 85)));
        txtNovoDado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNovoDadoMouseClicked(evt);
            }
        });
        txtNovoDado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNovoDadoKeyTyped(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(4, 191, 85));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Atualizar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(287, 287, 287))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(77, 77, 77))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(rbdados)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(rbendereco)
                                    .addGap(6, 6, 6))
                                .addComponent(cbDados, 0, 260, Short.MAX_VALUE)
                                .addComponent(txtNovoDado))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(jLabel6)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbdados)
                    .addComponent(rbendereco))
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbDados, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNovoDado, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtNovoDadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNovoDadoMouseClicked

    }//GEN-LAST:event_txtNovoDadoMouseClicked

    private void txtNovoDadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNovoDadoKeyTyped
        char charKey = evt.getKeyChar();
        String valorAtual = txtNovoDado.getText();

        if ("Número".equals(cbDados.getSelectedItem()) && !Character.isDigit(charKey)) {
            evt.consume();
            return;
        }
    }//GEN-LAST:event_txtNovoDadoKeyTyped

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        ConectaBD banco = new ConectaBD();
        controllerUsuario usuario = new controllerUsuario();
        controllerEndereco endereco = new controllerEndereco();
        String dado = (String) cbDados.getSelectedItem();
        String novodado = txtNovoDado.getText();
        String senhaoriginal = usuario.VerificarSenha(login.username);

        try {
            if ("Nome".equals(dado)) {
                usuario.AtualizarNome(login.username, novodado);
                JOptionPane.showInternalMessageDialog(null, "Atualização de dados realizado com sucesso!");
                txtNovoDado.setText("");
            } else if ("Nome de Usuario".equals(dado)) {
                String usuariof = JOptionPane.showInputDialog(null, "Digite sua senha para atualizar seu nome de usuario:");
                while (!usuariof.equals(senhaoriginal)) {
                    JOptionPane.showInternalMessageDialog(null, "Senha incorreta!");
                    usuariof = JOptionPane.showInputDialog(null, "Digite sua senha para atualizar seu nome de usuario:");
                    
                }
                usuario.AtualizarUsername(login.username, novodado);
                JOptionPane.showInternalMessageDialog(null, "Atualização de dados realizado com sucesso!");
                login.username = novodado;
                txtNovoDado.setText("");
            } else if ("Senha".equals(dado)) {
                String usuariof = JOptionPane.showInputDialog(null, "Digite sua senha para atualizar seu nome de usuario:");
                while (!usuariof.equals(senhaoriginal)) {
                    JOptionPane.showInternalMessageDialog(null, "Senha incorreta!");
                    usuariof = JOptionPane.showInputDialog(null, "Digite sua senha para atualizar seu nome de usuario:");
                    
                }
                usuario.AtualizarSenha(login.username, novodado);
                JOptionPane.showInternalMessageDialog(null, "Atualização de dados realizado com sucesso!");
                txtNovoDado.setText("");
            } else if ("Rua".equals(dado)) {
                endereco.AtualizarRua(login.username, novodado);
                JOptionPane.showInternalMessageDialog(null, "Atualização de dados realizado com sucesso!");
                txtNovoDado.setText("");
            } else if ("Número".equals(dado)) {
                int novodadonumero = Integer.parseInt(novodado);
                endereco.AtualizarNumeroCasa(login.username, novodadonumero);
                JOptionPane.showInternalMessageDialog(null, "Atualização de dados realizado com sucesso!");
                txtNovoDado.setText("");
            } else if ("Setor".equals(dado)) {
                endereco.AtualizarSetor(login.username, novodado);
                JOptionPane.showInternalMessageDialog(null, "Atualização de dados realizado com sucesso!");
                txtNovoDado.setText("");
            } else if ("Cidade".equals(dado)) {
                endereco.AtualizarCidade(login.username, novodado);
                JOptionPane.showInternalMessageDialog(null, "Atualização de dados realizado com sucesso!");
                txtNovoDado.setText("");
            } else if ("Estado".equals(dado)) {
                endereco.AtualizarEstado(login.username, novodado);
                JOptionPane.showInternalMessageDialog(null, "Atualização de dados realizado com sucesso!");
                txtNovoDado.setText("");
            } else if ("CEP".equals(dado)) {
                endereco.AtualizarCEP(login.username, novodado);
                JOptionPane.showInternalMessageDialog(null, "Atualização de dados realizado com sucesso!");
                txtNovoDado.setText("");
            } else if ("Complemento".equals(dado)) {
                endereco.AtualizarComplemento(login.username, novodado);
                JOptionPane.showInternalMessageDialog(null, "Atualização de dados realizado com sucesso!");
                txtNovoDado.setText("");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showInternalMessageDialog(null, "Erro: Insira um número válido para o campo Número.");
        } finally {
            banco.fecharConexao();
        }
    }//GEN-LAST:event_jButton2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbDados;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton rbdados;
    private javax.swing.JRadioButton rbendereco;
    private javax.swing.JTextField txtNovoDado;
    // End of variables declaration//GEN-END:variables
}
