/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package c.securebank.view;

import c.securebank.ConectaBD;
import c.securebank.controller.controllerCadastro;
import c.securebank.controller.controllerUsuario;
import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
         
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbLogo = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btclose = new javax.swing.JLabel();
        lbNascimento = new javax.swing.JLabel();
        txtNascimento = new javax.swing.JTextField();
        lbCPF = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        lbRG = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        lbDadosPessoais = new javax.swing.JLabel();
        lbEnderecoResidencial = new javax.swing.JLabel();
        lbRua = new javax.swing.JLabel();
        txtRG = new javax.swing.JTextField();
        lbNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lbSetor = new javax.swing.JLabel();
        txtSetor = new javax.swing.JTextField();
        lbCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lbEstado = new javax.swing.JLabel();
        lbCEP = new javax.swing.JLabel();
        txtCEP = new javax.swing.JTextField();
        lbComplemento = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        btFinalizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(102, 230, 128));
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(202, 219, 210));
        jPanel2.setForeground(new java.awt.Color(13, 13, 13));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        lbTitulo.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(51, 102, 92));
        lbTitulo.setText("CADASTRO C-SECUREBANK");

        jPanel1.setBackground(new java.awt.Color(26, 32, 44));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");

        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/c/securebank/resources/_9561f767-62c1-4cbe-8994-e13523ee38ba (1) (1)_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbLogo)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(lbLogo)
                .addGap(110, 110, 110))
        );

        lbNome.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lbNome.setForeground(new java.awt.Color(51, 102, 92));
        lbNome.setText("NOME COMPLETO");

        txtNome.setBackground(new java.awt.Color(202, 219, 210));
        txtNome.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtNome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(7, 173, 87)));
        txtNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNomeMouseClicked(evt);
            }
        });
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeKeyTyped(evt);
            }
        });

        btclose.setBackground(new java.awt.Color(255, 0, 0));
        btclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/c/securebank/resources/icons8-cancelar-32 (1).png"))); // NOI18N
        btclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btcloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btcloseMouseEntered(evt);
            }
        });

        lbNascimento.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lbNascimento.setForeground(new java.awt.Color(51, 102, 92));
        lbNascimento.setText("DATA DE NASCIMENTO");

        txtNascimento.setBackground(new java.awt.Color(202, 219, 210));
        txtNascimento.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtNascimento.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(7, 173, 87)));
        txtNascimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNascimentoMouseClicked(evt);
            }
        });
        txtNascimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNascimentoKeyTyped(evt);
            }
        });

        lbCPF.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lbCPF.setForeground(new java.awt.Color(51, 102, 92));
        lbCPF.setText("CPF");

        txtCPF.setBackground(new java.awt.Color(202, 219, 210));
        txtCPF.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtCPF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(7, 173, 87)));
        txtCPF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCPFMouseClicked(evt);
            }
        });
        txtCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCPFKeyTyped(evt);
            }
        });

        lbRG.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lbRG.setForeground(new java.awt.Color(51, 102, 92));
        lbRG.setText("RG");

        txtRua.setBackground(new java.awt.Color(202, 219, 210));
        txtRua.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtRua.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(7, 173, 87)));
        txtRua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRuaMouseClicked(evt);
            }
        });

        lbDadosPessoais.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lbDadosPessoais.setText("DADOS PESSOAIS");
        lbDadosPessoais.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbEnderecoResidencial.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lbEnderecoResidencial.setText("ENDEREÇO RESIDENCIAL");

        lbRua.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lbRua.setForeground(new java.awt.Color(51, 102, 92));
        lbRua.setText("RUA");

        txtRG.setBackground(new java.awt.Color(202, 219, 210));
        txtRG.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtRG.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(7, 173, 87)));
        txtRG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRGMouseClicked(evt);
            }
        });
        txtRG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRGKeyTyped(evt);
            }
        });

        lbNumero.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lbNumero.setForeground(new java.awt.Color(51, 102, 92));
        lbNumero.setText("NÚMERO");

        txtNumero.setBackground(new java.awt.Color(202, 219, 210));
        txtNumero.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtNumero.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(7, 173, 87)));
        txtNumero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNumeroMouseClicked(evt);
            }
        });
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });

        lbSetor.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lbSetor.setForeground(new java.awt.Color(51, 102, 92));
        lbSetor.setText("SETOR");

        txtSetor.setBackground(new java.awt.Color(202, 219, 210));
        txtSetor.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtSetor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(7, 173, 87)));
        txtSetor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSetorMouseClicked(evt);
            }
        });
        txtSetor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSetorKeyTyped(evt);
            }
        });

        lbCidade.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lbCidade.setForeground(new java.awt.Color(51, 102, 92));
        lbCidade.setText("CIDADE");

        txtCidade.setBackground(new java.awt.Color(202, 219, 210));
        txtCidade.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtCidade.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(7, 173, 87)));
        txtCidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCidadeMouseClicked(evt);
            }
        });
        txtCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCidadeKeyTyped(evt);
            }
        });

        lbEstado.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lbEstado.setForeground(new java.awt.Color(51, 102, 92));
        lbEstado.setText("ESTADO");

        lbCEP.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lbCEP.setForeground(new java.awt.Color(51, 102, 92));
        lbCEP.setText("CEP");

        txtCEP.setBackground(new java.awt.Color(202, 219, 210));
        txtCEP.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtCEP.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(7, 173, 87)));
        txtCEP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCEPMouseClicked(evt);
            }
        });
        txtCEP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCEPKeyTyped(evt);
            }
        });

        lbComplemento.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lbComplemento.setForeground(new java.awt.Color(51, 102, 92));
        lbComplemento.setText("COMPLEMENTO");

        txtComplemento.setBackground(new java.awt.Color(202, 219, 210));
        txtComplemento.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtComplemento.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(7, 173, 87)));
        txtComplemento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtComplementoMouseClicked(evt);
            }
        });

        btFinalizar.setBackground(new java.awt.Color(4, 191, 85));
        btFinalizar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btFinalizar.setForeground(new java.awt.Color(255, 255, 255));
        btFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/c/securebank/resources/icons8-verificado-32.png"))); // NOI18N
        btFinalizar.setText("FINALIZAR CADASTRO");
        btFinalizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btFinalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btFinalizar.setFocusPainted(false);
        btFinalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btFinalizarMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 92));
        jLabel1.setText("NOME DE USUÁRIO");

        txtUsuario.setBackground(new java.awt.Color(202, 219, 210));
        txtUsuario.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(7, 173, 87)));
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 92));
        jLabel2.setText("SENHA DE ACESSO:");

        txtPassword.setBackground(new java.awt.Color(202, 219, 210));
        txtPassword.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(7, 173, 87)));
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
        });

        txtEstado.setBackground(new java.awt.Color(202, 219, 210));
        txtEstado.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtEstado.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(7, 173, 87)));
        txtEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEstadoMouseClicked(evt);
            }
        });
        txtEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEstadoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(lbTitulo)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(btclose))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbDadosPessoais)
                                    .addComponent(lbEnderecoResidencial)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lbRua, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lbNumero)
                                                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lbCidade))
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGap(30, 30, 30)
                                                        .addComponent(lbSetor))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGap(30, 30, 30)
                                                        .addComponent(txtSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGap(113, 113, 113)
                                                        .addComponent(lbEstado))))
                                            .addComponent(lbNome)
                                            .addComponent(lbNascimento)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtEstado))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lbCEP))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lbComplemento)
                                                    .addComponent(txtComplemento)))
                                            .addComponent(txtNome)
                                            .addComponent(txtNascimento)
                                            .addComponent(txtRua)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel1)
                                                    .addComponent(lbCPF))
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(lbRG)
                                                            .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGap(12, 12, 12)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btclose))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lbTitulo)))
                .addGap(37, 37, 37)
                .addComponent(lbDadosPessoais)
                .addGap(9, 9, 9)
                .addComponent(lbNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbNascimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCPF)
                    .addComponent(lbRG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbEnderecoResidencial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbRua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNumero)
                    .addComponent(lbSetor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbCidade)
                    .addComponent(lbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbComplemento)
                    .addComponent(lbCEP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked

    }//GEN-LAST:event_jPanel2MouseClicked

    private void txtNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomeMouseClicked

    }//GEN-LAST:event_txtNomeMouseClicked

    private void btcloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btcloseMouseEntered
        btclose.setBackground(new Color(255, 0, 0));
    }//GEN-LAST:event_btcloseMouseEntered

    private void btcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btcloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btcloseMouseClicked

    private void txtNascimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNascimentoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNascimentoMouseClicked

    private void txtCPFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCPFMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFMouseClicked

    private void txtRuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRuaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuaMouseClicked

    private void txtRGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRGMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRGMouseClicked

    private void txtNumeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumeroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroMouseClicked

    private void txtSetorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSetorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSetorMouseClicked

    private void txtCidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCidadeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeMouseClicked

    private void txtCEPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCEPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCEPMouseClicked

    private void txtComplementoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtComplementoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplementoMouseClicked

    private void txtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioMouseClicked

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordMouseClicked

    private void txtNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyTyped
        char charKey = evt.getKeyChar();

        if (Character.isDigit(charKey)) {
            evt.consume();
        }

        String ValorAtual = txtNome.getText() + charKey;

        if (ValorAtual.length() < 10) {
            lbNome.setForeground(Color.red);
            lbNome.setText("Nome Inválido");
        } else {
            lbNome.setText("NOME");
            lbNome.setForeground(new Color(51, 102, 92));
        }
    }//GEN-LAST:event_txtNomeKeyTyped

    private void txtNascimentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNascimentoKeyTyped
        char charKey = evt.getKeyChar();

        if (!Character.isDigit(charKey)) {
            evt.consume();
        }

        String ValorAtual = txtNascimento.getText() + charKey;

        if (ValorAtual.length() < 8) {
            lbNascimento.setForeground(Color.red);
            lbNascimento.setText("Nascimento Inválido");
        } else if (ValorAtual.length() == 8) {
            lbNascimento.setText("NASCIMENTO");
            lbNascimento.setForeground(new Color(51, 102, 92));
            txtNascimento.setText(formatoNascimento(ValorAtual));
            evt.consume();
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_txtNascimentoKeyTyped

    private void txtCPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPFKeyTyped
        char charKey = evt.getKeyChar();

        if (!Character.isDigit(charKey)) {
            evt.consume();
        }

        String ValorAtual = txtCPF.getText() + charKey;

        if (ValorAtual.length() < 11) {
            lbCPF.setForeground(Color.red);
            lbCPF.setText("CPF Inválido");
        } else if (ValorAtual.length() == 11) {
            lbCPF.setText("CPF");
            lbCPF.setForeground(new Color(51, 102, 92));
            txtCPF.setText(formatoCPF(ValorAtual));
            evt.consume();
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_txtCPFKeyTyped

    private void txtRGKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRGKeyTyped
        char charKey = evt.getKeyChar();

        if (!Character.isDigit(charKey)) {
            evt.consume();
        }

        String ValorAtual = txtRG.getText() + charKey;

        if (ValorAtual.length() < 7) {
            lbRG.setForeground(Color.red);
            lbRG.setText("RG Inválido");
        } else if (ValorAtual.length() == 7) {
            lbRG.setText("RG");
            lbRG.setForeground(new Color(51, 102, 92));
            txtRG.setText(formatoRG(ValorAtual));
            evt.consume();
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_txtRGKeyTyped

    private void txtSetorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSetorKeyTyped
        char charKey = evt.getKeyChar();

        if (Character.isDigit(charKey)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtSetorKeyTyped

    private void txtCidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCidadeKeyTyped
        char charKey = evt.getKeyChar();

        if (Character.isDigit(charKey)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCidadeKeyTyped

    private void txtCEPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCEPKeyTyped
        char charKey = evt.getKeyChar();

        if (!Character.isDigit(charKey)) {
            evt.consume();
        }

        String ValorAtual = txtCEP.getText() + charKey;

        if (ValorAtual.length() < 8) {
            lbCEP.setForeground(Color.red);
            lbCEP.setText("CEP Inválido");
        } else if (ValorAtual.length() == 8) {
            lbCEP.setText("CEP");
            lbCEP.setForeground(new Color(51, 102, 92));
            txtCEP.setText(formatoCEP(ValorAtual));
            evt.consume();
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_txtCEPKeyTyped

    private void btFinalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFinalizarMouseClicked
        String nome = txtNome.getText();
        String nascimento = txtNascimento.getText();
        String CPF = txtCPF.getText();
        String RG = txtRG.getText();
        Double saldo = 0.00;
        String usuario = txtUsuario.getText();
        String senha = txtPassword.getText();
        int numeroConta = GeradorNumeroConta();
        String rua = txtRua.getText();
        int numero = Integer.parseInt(txtNumero.getText());
        String setor = txtSetor.getText();
        String cidade = txtCidade.getText();
        String estado = txtEstado.getText();
        String cep = txtCEP.getText();
        String complemento = txtComplemento.getText();

        controllerCadastro cadastro = new controllerCadastro();
        controllerUsuario verificacao = new controllerUsuario();
        ConectaBD banco = new ConectaBD();
        

        try {    
            boolean ContaExiste = verificacao.verificarNumeroContaExistente(numeroConta);
            while (ContaExiste) {
                numeroConta = GeradorNumeroConta();            
            }
            SimpleDateFormat formatoEntrada = new SimpleDateFormat("dd/MM/yyyy");
            
            // Converte a string para um objeto Date usando o formato de entrada
            Date data = formatoEntrada.parse(nascimento);

            // Define o formato de saída
            SimpleDateFormat formatoSaida = new SimpleDateFormat("yyyy/MM/dd");

            // Converte o objeto Date para uma string usando o formato de saída
            String dataFormatada = formatoSaida.format(data);
            
            int EnderecoID = cadastro.inserirEndereco(rua, numero, setor, cidade, estado, cep, complemento);
            cadastro.inserirUsuario(nome, dataFormatada, CPF, RG, saldo, usuario, senha, numeroConta,EnderecoID);
            System.out.println("Cadastro realizado com sucesso!");
            this.dispose();
            login janela = new login();
            janela.setVisible(true);
            janela.setLocationRelativeTo(null);
            
        } catch (SQLException ex) {
            System.out.println("Erro ao inserir endereço: " + ex.getMessage());
        } catch (ParseException ex) {
            Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            banco.fecharConexao();
        }
    }//GEN-LAST:event_btFinalizarMouseClicked

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void txtEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEstadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoMouseClicked

    private void txtEstadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstadoKeyTyped
        char charKey = evt.getKeyChar();

        if (Character.isDigit(charKey)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtEstadoKeyTyped

    private static String formatoCPF(String valor) {
        if (valor.length() == 11) {
            return String.format("%s.%s.%s-%s",
                    valor.substring(0, 3),
                    valor.substring(3, 6),
                    valor.substring(6, 9),
                    valor.substring(9));
        } else {
            return valor; // Retorna o valor original se não estiver completo
        }
    }

    private static String formatoRG(String valor) {
        if (valor.length() == 7) {
            return String.format("%s-%s",
                    valor.substring(0, 6),
                    valor.substring(6));
        } else {
            return valor; // Retorna o valor original se não estiver completo
        }
    }

    private static String formatoCEP(String valor) {
        if (valor.length() == 8) {
            return String.format("%s-%s",
                    valor.substring(0, 5),
                    valor.substring(5));
        } else {
            return valor; // Retorna o valor original se não estiver completo
        }
    }

    private static String formatoNascimento(String valor) {
        if (valor.length() == 8) {
            return String.format("%s/%s/%s",
                    valor.substring(0, 2),
                    valor.substring(2, 4),
                    valor.substring(4));
        } else {
            return valor; // Retorna o valor original se não estiver completo
        }
    }

    private static int GeradorNumeroConta() {
        Random random = new Random();
        int numeroAleatorio = random.nextInt(900000) + 100000;
        return numeroAleatorio;
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFinalizar;
    private javax.swing.JLabel btclose;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbCEP;
    private javax.swing.JLabel lbCPF;
    private javax.swing.JLabel lbCidade;
    private javax.swing.JLabel lbComplemento;
    private javax.swing.JLabel lbDadosPessoais;
    private javax.swing.JLabel lbEnderecoResidencial;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbNascimento;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNumero;
    private javax.swing.JLabel lbRG;
    private javax.swing.JLabel lbRua;
    private javax.swing.JLabel lbSetor;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField txtCEP;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNascimento;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtRG;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtSetor;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
